on:
  pull_request:
  push:
    branches: [ 'master' ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: |
          if ('${{ github.event_name == 'push' && github.ref_type == 'tag' }}' -eq 'true') {
            $ver = $env:GITHUB_REF -replace '^refs/tags/v'
          } else {
            $ver = '0.0.0'
          }

          dotnet.exe publish AutoAudioSwitcher -o publish -p:Version="$ver"
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' .\Setup\Setup.iss

      - name: Create release draft
        if: github.event_name == 'push' && github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = $env:GITHUB_REF -replace '^refs/tags/'
          gh release create --draft --title $tag $tag Setup\Output\AutoAudioSwitcher-Setup.exe
