on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          $ver = '${{ github.event.release.tag_name }}'.TrimStart('v')
          dotnet.exe publish AutoAudioSwitcher -o publish -p:Version="$ver"
          Compress-Archive -Path publish\* -DestinationPath "AutoAudioSwitcher-$ver.zip"

      - name: Upload release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} (Get-Item *.zip)
